# 指定运行端口
server:
  port: 8001

# 指定服务名称
spring:
  application:
    name: eureka-server

# 指定主机地址
eureka:
  # 驱逐下线的服务，间隔5秒，默认60秒
#  server:
#    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: false
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: false