server:
  port: 8905

spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrGwei/ConfigFile
          username: MrGwei
          password:
          search-paths: respo
          clone-on-start: true
  security:
    user:
      name: root
      password: root1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/