server:
  port: 8904

spring:
  application:
    name: config-server
  cloud:
    config:
      #      label: master
      server:
        git:
          # 配置存储配置信息的Git仓库
          clone-on-start: true
          # 配置存储配置信息的Git仓库
          uri: https://github.com/MrGwei/ConfigFile
          search-paths: respo
          #search-paths: '{application}'
          username: MrGwei
          password:
  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
