server:
  port: 8308
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: 192.168.6.180
      port: 8500
      discovery:
        hostname: 192.168.6.111
        # 实例ID
#        service-name: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        # 健康检查
        health-check-path: /actuator/health
        health-check-interval: 10s
        heartbeat:
          enabled: true

service-url:
  consul-user-service: http://consul-user-service